blank_issues_enabled: false
contact_links:
  - name: "Cyvize: Scorched Earth"
    url: https://cyvive.art
    about: Parent Project, information on existing in CyberSpace, PlanetScale
  - name: Cyvizen
    url: https://cyvizen.art
    about: Purchase Cyvizen approved hardware, use commercial support
